[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'php82Extensions.gd', 'apache2']

[phases.install]
cmds = ['echo "Installing dependencies..."']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'frankenphp run --config /etc/caddy/Caddyfile'

[variables]
NIXPACKS_PHP_ROOT_DIR = '/'
PORT = '8080'
